// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../../github.com/google/uuid/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * AuthUser авторизация пользователя.
 */
export function AuthUser(userData: models$0.UserData): $CancellablePromise<models$0.UserData> {
    return $Call.ByID(317369557, userData).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CheckPinCode(pinCode: string, userUuid: uuid$0.UUID): $CancellablePromise<void> {
    return $Call.ByID(958010274, pinCode, userUuid);
}

/**
 * CreateUser создание нового пользователя.
 */
export function CreateUser(userData: models$0.UserData): $CancellablePromise<[string, string]> {
    return $Call.ByID(2443194051, userData);
}

/**
 * RecoveryUser смена пароля пользователя по коду восстановления.
 * принимает код восстановления, новый пароль и юзернейм пользователя.
 */
export function RecoveryUser(recoveryCode: string, passNew: string, username: string): $CancellablePromise<string> {
    return $Call.ByID(3434687432, recoveryCode, passNew, username);
}

export function SetupPinCode(pinCode: string, userUuid: uuid$0.UUID): $CancellablePromise<void> {
    return $Call.ByID(173562277, pinCode, userUuid);
}

// Private type creation functions
const $$createType0 = models$0.UserData.createFrom;
